In [1]:
import pandas as pd

In [2]:
# Importar datos desde un archivo existente

datos = pd.read_csv("Datos/test-data.csv")
datos.head(5)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN

In [3]:
# Importar datos desde una URL

url = "/kaggle/input/cars-dataset/used_cars_data.csv"
datos = pd.read_csv(url)
datos.head(5)

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/cars-dataset/used_cars_data.csv'

In [ ]:
# IMporta datos sin la cabeera

url = "/kaggle/input/cars-dataset/used_cars_data.csv"
datos = pd.read_csv(url, header=None)
datos.head(5)

In [4]:
# Imprimir ultimas columnas dataframes desde python 
datos.tail(5)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
1229,1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
1230,1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
1231,1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
1232,1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN
1233,1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN

In [5]:
# Reemplazar datos de la cadecera

headers = ["ID", "Modelo", "Locacion", "Año", "Kilometros_Recorridos", "Tipo_Combustible", "Transmision", "Dueños", "Millas_Recorridas", "Cilindraje", "Potencia", "Asientos", "Nuevo_Precio"]
datos.columns =headers
datos.head(5)

,ID,Modelo,Locacion,Año,Kilometros_Recorridos,Tipo_Combustible,Transmision,Dueños,Millas_Recorridas,Cilindraje,Potencia,Asientos,Nuevo_Precio
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN

In [6]:
# Guardar le progreso de los cambios

path ="Datos/Automoviles.csv"

datos.to_csv(path)